title: Md Mainul Hasan Sarker, PhD
#logo:
description: Dr. Md Mainul Hasan Sarker is a Postdoctoral Research Scholar specializing in epigenomics and transcriptomics, with a focus on uncovering biomarkers and molecular mechanisms underlying PTSD and cardiovascular disease.
show_downloads: true
theme: jekyll-theme-architect

