title: Md Mainul Hasan Sarker, PhD
#logo:
description: Researcher and Data Scientist specializing in epigenomics, transcriptomics and  Chronic Disease Prediction, with a focus on uncovering biomarkers and molecular mechanisms underlying Stress exprouser and its modification. Current focus on PTSD and cardiovascular disease.
show_downloads: true
theme: jekyll-theme-minimal

